# Generated by Django 5.0.2 on 2024-04-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='market',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='symbol',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='stockprice',
            old_name='symbol',
            new_name='ticker',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sector',
        ),
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
