# Generated by Django 5.0.2 on 2024-05-10 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data_app', '0004_alter_stockprice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 0, 33, 57, 994267)),
        ),
    ]
