# Generated by Django 5.0.2 on 2024-05-11 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data_app', '0006_alter_stock_id_alter_stockprice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 3, 29, 1, 61091)),
        ),
    ]
