# Generated by Django 5.0.2 on 2024-02-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_and_profiles', '0004_profile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
